### ISSUE TITLE
OpenIAB can't consume product  ( iOS , Unity3D) !!!

### ISSUE THREAD

**Issue by Armnomads** [onepf/OpenIAB-Unity-Plugin#83]
Hi all.
I have an issue with consumable products.
When i purchase consumable item , and then consume it , events not  works (consumeSucceded or consumeFailed) ,
But i able buy them every  time (still without events) .

private void purchaseSucceededEvent(Purchase purchase)
{
		if(purchase.Sku == "mySku")
			OpenIAB.consumeProduct(purchase);

         Debug.Log (purchase.Sku);  //  this shows my sku 
}

// not called
private void consumePurchaseSucceededEvent(Purchase product)
{
}

// not called
private void consumePurchaseFailedEvent(Purchase product)
{
}

everything works fine with only non-consumable items ...

pls help !!!

**Comment by akarimova** [comment]
Hello @Armnomads 
Do you have any logs?

**Comment by unityguy** [comment]
In OpenIAB v0.9.8.6 (latest release as of writing), the purchase succeeded event returns the store SKU of the product instead of the original SKU (on iOS) but the `OpenIAB.consumeProduct` method expects the original SKU. In the purchase succeeded event, I re-create the purchase object like this:

    purchase = new Purchase(new JSON(purchase.Serialize()));

After this, the purchase has the original SKU and I can call `OpenIAB.consumeProduct(purchase)`.

I hope this helps.

**Comment by unityguy** [comment]
@akarimova can you check out my question, please?

https://github.com/onepf/OpenIAB-Unity-Plugin/issues/82
